server:
  port: 8011

spring:
  devtools:
    restart:
      enabled: true
  redis:
      host: 114.116.48.131
      password:
      port: 9001
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1

